services:
  badge_maker_api:
    container_name: badge_maker_api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks: # Port 5000
      - main_sites
    restart: always

  badge_maker_frontend:
    container_name: badge_maker_frontend
    build:
      context: ./app
      dockerfile: Dockerfile
    networks: # Port 3000
      - main_sites
    restart: always
    depends_on:
      - api

networks:
  main_sites:
    external: true
