---
services:
  badge_maker_api:
    container_name: badge_maker_api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks: # Port 5000
      - main_sites
    restart: always

  badge_maker_frontend:
    container_name: badge_maker_frontend
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://badge-maker-api.jukelyn.com}
    networks: # Port 3000
      - main_sites
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=https://badge-maker-api.jukelyn.com
    depends_on:
      - badge_maker_api

networks:
  main_sites:
    external: true
