---
name: Lint Code Base

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v7.3.0
        env:
          VALIDATE_JAVASCRIPT_STANDARD: false # Disable the default JS linter
          VALIDATE_TYPESCRIPT_ESLINT: true
          TYPESCRIPT_ESLINT_CONFIG_FILE: eslint.config.mjs
          FILTER_REGEX_EXCLUDE: "(README.md|\\.github/.*)" # Removed the error-specific exclusion
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYINK: false
          VALIDATE_GITHUB_ACTIONS: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
